"""Shared SDK constants."""

from importlib.metadata import PackageNotFoundError, version

DEFAULT_BASE_URL = "https://sandbox.brimble.io"
DEFAULT_TIMEOUT_MS = 30_000
SANDBOX_API_KEY_ENV_NAME = "BRIMBLE_SANDBOX_KEY"

try:
    SDK_PACKAGE_VERSION = version("brimble-sandbox")
except PackageNotFoundError:
    SDK_PACKAGE_VERSION = "0.1.2"

DEFAULT_PAGE = 1
DEFAULT_PAGE_LIMIT = 15
MAX_PAGE_LIMIT = 100
MIN_VOLUME_SIZE_GB = 10
DEFAULT_SANDBOX_READY_TIMEOUT_MS = 60_000
DEFAULT_SANDBOX_READY_POLL_INTERVAL_MS = 500
DEFAULT_SANDBOX_WAIT_POLL_INTERVAL_MS = 100
DEFAULT_SANDBOX_LONG_POLL_TIMEOUT_SECONDS = 60

DEFAULT_RETRY_MAX_ATTEMPTS = 1
DEFAULT_RETRY_BASE_DELAY_MS = 300
DEFAULT_RETRY_MAX_DELAY_MS = 3_000
DEFAULT_RETRY_STATUSES = (408, 429, 500, 502, 503, 504)
DEFAULT_RETRY_METHODS = ("GET", "DELETE", "PUT")
